## This image should only be used to build pulse-webapp

FROM node:alpine
LABEL description="AWS Amplify Dev Container"

ARG SSH_KEY
ARG GIT_USER_EMAIL
ARG GIT_USER_NAME

RUN apk add --no-cache vim screen openssh git bash curl
RUN curl --compressed -o- -L https://yarnpkg.com/install.sh | bash


# Make ssh dir
RUN mkdir /root/.ssh/
# Create id_rsa from string arg, and set permissions
RUN echo "$SSH_KEY" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Create known_hosts
RUN touch /root/.ssh/known_hosts

# Add git providers to known_hosts
RUN ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN ssh-keyscan gitlab.com >> /root/.ssh/known_hosts
RUN git config --global user.email "$GIT_USER_EMAIL"
RUN git config --global user.name "$GIT_USER_NAME"

RUN mkdir -p /usr/app

WORKDIR /usr/app
